apiVersion: apps/v1
kind: Deployment
metadata:
  name: electro-shop-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: electro-shop-app
  template:
    metadata:
      labels:
        app: electro-shop-app
    spec:
      containers:
        - name: electro-shop-app
          image: techadvocate247/electro-shop:1.0.0-10
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
