apiVersion: v1
kind: Service
metadata:
  name: electro-shop-app-service
  labels:
    app: electro-shop-app 
spec:
  selector:
    app: electro-shop-app

  ports:
    - port: 80
      targetPort: 80

  type: LoadBalancer